# inspired from https://docs.gitlab.com/ee/user/packages/container_registry/
# define the stages for this CI as well as the images to pull and services to use
image: docker:20.10.21
services:
  - docker:20.10.16-dind
stages:
  - build
  - release
  - gke-deploy

# declare the variables used within the CI and eventually docker files
variables:
  WORKDIR: "news_bias_evaluator"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  KUBE_CONTEXT: "courses/dit825/2022/group07/group-07:dit825-cluster-agent"

# setup the environment before running the different scripts
default: #default lets us exclude the before script from the gke-deployment stage
  before_script:
    # update an upgrade
    - apk update
    - apk upgrade
    # install docker compose
    - apk add docker-compose
    # Print info to check that everything is installed as it should
    - docker --version
    - docker-compose --version
    # login to the docker deamon
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    # go into working directory
    - cd $WORKDIR

# run the build step
build:
  # define which runner to use
  tags:
    - docker-build
  stage: build
  script:
    #build the docker image using docker compose
    - docker-compose build

#run the release step
release:
  # define which runner to use
  tags:
    - docker-build
  stage: release
  script:
    # build the docker image using docker compose
    - docker-compose build
    # add the tag "latest" to the image for release
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    # push to registry
    - docker push $CONTAINER_RELEASE_IMAGE
  # runs only if changes are happening on main branch
  only:
    - main

deploy:
  inherit:
    default: false # gke-deployment job wont inherit any default: keys (in this case, the before_script)
  stage: gke-deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  # define which runner to use
  tags:
    - docker-build
  script:
    - kubectl config get-contexts
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f $CI_PROJECT_DIR/k8s_manifests/news-bias-evaluator-app-deployment.yaml
