# Generated by Django 4.1.3 on 2022-12-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('news_link', models.CharField(max_length=200)),
                ('outlet', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('political_type', models.CharField(max_length=10)),
                ('group_id', models.IntegerField()),
                ('num_sent', models.IntegerField()),
                ('label_bias', models.CharField(max_length=10)),
                ('label_opinion', models.CharField(max_length=50)),
                ('article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bias_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.entry')),
            ],
        ),
    ]
