# Generated by Django 4.1.3 on 2022-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bias_word',
            name='word',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
