# Generated by Django 4.1 on 2022-12-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='initialEntry',
            fields=[
                ('sentence', models.TextField(primary_key=True, serialize=False)),
                ('news_link', models.CharField(max_length=200)),
                ('outlet', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('political_type', models.CharField(max_length=10)),
                ('group_id', models.IntegerField()),
                ('num_sent', models.IntegerField()),
                ('label_bias', models.CharField(max_length=10)),
                ('label_opinion', models.CharField(max_length=50)),
                ('article', models.TextField()),
                ('bias_words', models.TextField()),
            ],
        ),
    ]
