# Generated by Django 4.1.3 on 2022-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_news_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='political_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='labeledsentence',
            name='label_bias',
            field=models.CharField(max_length=30),
        ),
    ]
