# Generated by Django 4.1.3 on 2022-12-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_political_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='outlet',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=30),
        ),
    ]
