# Generated by Django 4.1.3 on 2022-12-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_request_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('version_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('true_positive', models.IntegerField()),
                ('false_positive', models.IntegerField()),
                ('false_negative', models.IntegerField()),
                ('true_negative', models.IntegerField()),
            ],
        ),
    ]
