# Generated by Django 4.1.3 on 2023-01-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_request_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='filename',
            field=models.TextField(default='non provided'),
            preserve_default=False,
        ),
    ]
