# Generated by Django 4.1.3 on 2023-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='filename',
        ),
        migrations.AddField(
            model_name='labeledsentence',
            name='filename',
            field=models.TextField(default='not provided'),
        ),
    ]
