# Generated by Django 4.1.3 on 2023-01-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_article_news_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('version_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('true_positive', models.IntegerField()),
                ('false_positive', models.IntegerField()),
                ('false_negative', models.IntegerField()),
                ('true_negative', models.IntegerField()),
            ],
        ),
    ]
