version: '3'

services:
    web:
        image: "${IMAGE_TAG}" # Uses the variable defined in Docker_CI.yml as image name
        build: .
        command: python manage.py runserver localhost:8000
        ports: 
            - 8000:8000
