apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-bias-evaluator-app
spec:
  # let's us define which pods (based on pod labels) should be affected by this deployment.
  # type command: " kubectl explain deployment.spec.selector | more " for more info
  selector:
    matchLabels:
      app: news-bias-evaluator-app
  replicas: 2
  template:
    metadata:
      labels:
        app: news-bias-evaluator-app
    spec:
      # registry credentials were deployed manually to the cluster.
      # Keys contain base 64 encoding for security reasoons.
      # The following two lines tell the deployment file to use these credentials
      # to pull the docker image from the private registry
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8080
          name: news-bias-evaluator-app
          #image: registry.git.chalmers.se/courses/dit825/2022/group07/group-07:latest
          # Limits the resourced dedicated to each pod.
          image: marble879/dockerhub:second-image
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080

---
# Make the deployment accessible from within the cluster
apiVersion: v1
kind: Service
metadata:
  name: news-bias-evaluator-app
  labels:
    app: news-bias-evaluator-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: news-bias-evaluator-app
